title: DApp Meeting
description: Ứng dụng họp trực tuyến phi tập trung kết hợp giữa công nghệ blockchain và WebRTC
theme: jekyll-theme-cayman
readme_index:
  enabled: true
  remove_originals: false

---
layout: default
---

{% include_relative README.md %}